name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker_job:
    name: Docker Job
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        if: github.event_name == 'push'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build (and push if main branch)
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name == 'push' }}
          tags: dariusmurawski/lunarvim:latest
      -
        name: Image digest
        if: github.event_name == 'push'
        run: echo ${{ steps.docker_build.outputs.digest }}

